version: '3.8'
services:
  app:
    build: .
    image: web-ser
    networks:
      - mynet
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 15328
      DB_NAME: planner
      DB_PORT: 5432
  db:
    image: postgres:15
    networks:
      - mynet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15328
      POSTGRES_DB: planner
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  mynet:
    external: true